version: '2'
services:

#  s5r-consul:
#    container_name: 's5r-consul'
#    image: progrium/consul:latest
#    command: -server -bootstrap -ui-dir /ui
#    restart: always
#    mem_limit: 128m
#    ports:
#      - 8500:8500
#    expose:
#      - 53
#      - 8300
#      - 8301
#      - 8302
#      - 8400
#      - 8500
#    dns:
#      - 127.0.0.1

  s5r-rabbitmq:
    container_name: 's5r-rabbitmq'
    image: rabbitmq:3.6.6-management
    ports:
      - "8080:15672"
      - "5672:5672"

  s5r-scheduler:
    container_name: 's5r-scheduler'
    image: stefanwalther/sammler-scheduler:master
    environment:
      - SAMMLER_RABBITMQ_URL=amqp://guest:guest@s5r-rabbitmq:5672
    links:
      - s5r-rabbitmq

  # Middleware GitHub
  s5r-middleware-github-db:
    container_name: 's5r-middleware-github-db'
    image: postgres:9.6
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=postgres
      - POSTGRES_DB=sammler-github
    volumes:
      - postgres_data:/var/lib/postgresql/data

  s5r-middleware-github:
    container_name: 's5r-middleware-github'
    image: stefanwalther/sammler-middleware-github:latest
    environment:
      - SAMMLER_MIDDLEWARE_GITHUB_PORT=3001
    links:
      - s5r-middleware-github-db
      - s5r-rabbitmq

  # Middleware LinkedIn


volumes:
  postgres_data:
