version: '2'
services:

  # --------------------------------------------------------------------------------------------------------------------
  # Base Services
  # --------------------------------------------------------------------------------------------------------------------
  s5r-mongo:
    extends:
      file: ./node_modules/sammler-base/docker-compose.yml
      service: s5r-mongo

  s5r-rabbitmq:
    extends:
      file: ./node_modules/sammler-base/docker-compose.yml
      service: s5r-rabbitmq

  # Infastructure services

#  s5r-consul:
#    container_name: 's5r-consul'
#    image: progrium/consul:latest
#    command: -server -bootstrap -ui-dir /ui
#    restart: always
#    mem_limit: 128m
#    ports:
#      - 8500:8500
#    expose:
#      - 53
#      - 8300
#      - 8301
#      - 8302
#      - 8400
#      - 8500
#    dns:
#      - 127.0.0.1

  # --------------------------------------------------------------------------------------------------------------------
  # sammler services
  # --------------------------------------------------------------------------------------------------------------------
  s5r-scheduler-service:
    build:
      context: ./node_modules/sammler-scheduler-service
    environment:
      - PORT=3002
      - SAMMLER_RABBITMQ_URI=amqp://guest:guest@s5r-rabbitmq:5672
      - SAMMLER_JOBS_SERVICE_URI=http://s5r-jobs-service:3003
      - SAMMLER_LOG_SERVICE_URI=http://s5r-log-service:3004
    volumes:
      - ./node_modules/sammler-scheduler-service/:/home
    links:
      - s5r-rabbitmq
      - s5r-mongo
    command: yarn run start:dev


  s5r-jobs-service:
    build:
      context: ./node_modules/sammler-jobs-service
    environment:
      - PORT=3003
      - WAIT_COMMAND=[ $$(curl --write-out %{http_code} --silent --output /dev/null http://s5r-mongo:27017) = 200 ]
      - WAIT_START_CMD=yarn run start:dev
      - WAIT_SLEEP=2
      - WAIT_LOOPS=20
      - SAMMLER_DB_JOBS_URI=mongodb://s5r-mongo:27017/jobs
    volumes:
      - ./node_modules/sammler-jobs-service/:/home
    links:
      - s5r-mongo
    command: sh wait_to_start.sh

  s5r-log-service:
    build:
      context: ./node_modules/sammler-log-service
    environment:
      - PORT=3004
      - WAIT_COMMAND=[ $$(curl --write-out %{http_code} --silent --output /dev/null http://s5r-mongo:27017) = 200 ]
      - WAIT_START_CMD=yarn run start:dev
      - WAIT_SLEEP=2
      - WAIT_LOOPS=20
      - SAMMLER_DB_URI_LOGS=mongodb://s5r-mongo:27017/logs
    volumes:
      - ./node_modules/sammler-log-service/:/home
    links:
      - s5r-mongo
    command: sh wait_to_start.sh

  s5r-strategy-github:
    build:
      context: ./node_modules/sammler-strategy-github
    environment:
      - PORT=3100
      - SAMMLER_STRATEGY_GITHUB_DB_URI=mongodb://s5r-mongo:27017/github
      - SAMMLER_RABBITMQ_URI=amqp://guest:guest@s5r-rabbitmq:5672
      - WAIT_COMMAND=[ $$(curl --write-out %{http_code} --silent --output /dev/null http://s5r-mongo:27017) = 200 ]
      - WAIT_START_CMD=yarn run start:dev
      - WAIT_SLEEP=2
      - WAIT_LOOPS=20
    volumes:
          - ./node_modules/sammler-strategy-github/:/home
    links:
      - s5r-mongo
      - s5r-rabbitmq
      - s5r-scheduler-service
      - s5r-jobs-service
      - s5r-log-service
    command: sh wait_to_start.sh

