version: '2'
services:

  sammler-consul:
    container_name: 's5r-consul'
    image: progrium/consul:latest
    command: -server -bootstrap -ui-dir /ui
    restart: always
    mem_limit: 128m
    ports:
      - 8500:8500
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    dns:
      - 127.0.0.1

  sammler-rabbitmq:
    container_name: 's5r-rabbitmq'
    image: rabbitmq:3.6.6-management
    ports:
      - "8080:15672"
      - "5672:5672"
