version: '2'
services:
  # Load Balancing
  consul:
    image: progrium/consul:latest
    command: -server -bootstrap -ui-dir /ui
    restart: always
    mem_limit: 128m
    ports:
      - 8500:8500
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    dns:
      - 127.0.0.1

  nginx-lb:
    build: docker/nginx/
    mem_limit: 128m
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
    expose:
      - 8000
      - 8443
      - 8001
    links:
      - consul:consul
    restart: always
    command: >
        /bin/containerpilot
        -config file:///etc/containerpilot/containerpilot.json
        nginx -g "daemon off;"

